spring:
  profiles:
    active: dev



github:
  client:
    id: 
    secret: 
  redirect:
    uri: http://localhost:8080/callback


aliyun:
  ufile:
    public-key: 
    private-key: 
    bucketName: 
    endpoint: 
logging:
  file:
    path: community.log
  level:
    com:
      lhjitem:
        community:
          mapper: debug
    root: info
